### PR TITLE
fix mistakes

### PR DESCRIPTION
**Pull request by slytomcat**
Sorry, I've missed some mistakes in code after finishing debugging.
Please apply this PR to make pingbot working again

### CODE REVIEW

**Comment by stTheme** [comment]
Thank you for your contribution. I've already fixed these mistakes, added (changed) comments in the code and pushed version 1.1/latest to docker hub.

**Comment by slytomcat** [comment]
It seems that docker still contain old code.
I've updated docker to latest version.
For badhost.zzz in configuration file I'm receiving many errors messages instead of one (Unresolved).

**Comment by stTheme** [comment]
It's probably not the code itself but the exception part of the code... Where is no old code, I can tell you that.

**Comment by stTheme** [comment]
I pushed the latest version of the code. I didn't test it against bad hosts though.

**Comment by stTheme** [comment]
You can check it with docker exec -ti pingbot /bin/bash and then cat main.py

**Comment by slytomcat** [comment]
root@s-t-c:/opt/pingbot# docker pull alsoeast/pingbot
Using default tag: latest
latest: Pulling from alsoeast/pingbot
Digest: sha256:cff493b34554585d1cfba6921f3b44467284d5e71beaf741a6f90b6a0b321418
Status: Image is up to date for alsoeast/pingbot:latest
root@s-t-c:/opt/pingbot# docker-compose up&
[1] 13564
root@s-t-c:/opt/pingbot# Creating pingbot ... 
Creating pingbot ... done
Attaching to pingbot
.... some exception report...
root@s-t-c:/opt/pingbot# docker exec -ti pingbot /bin/bash
root@27aa9bdd5636:/usr/src/app# cat /usr/src/app/main.py 
from telegram import Bot
....
def ping_url(url):

    i = 0;

    try:
        response_list = ping(url)

        for response in response_list:
            if (not response.success):
                i += 1

        if (i == 4):
            return False
        else:
            return True
            
    except Exception as e:
        send_message(str(e))
...
____
it is old/primary version of ping_url that send every exeptions of ping.

New one just return None in case of exeception.

**Comment by stTheme** [comment]
Try pingbot 1.1 Maybe it was my mistake to trust docker to update image. Maybe it's my mistake all along.

**Comment by slytomcat** [comment]
1.1 - has the same (old) code.

**Comment by stTheme** [comment]
No it's not. Somethings wrong with your setup.

(ve) [denko@denko pingbot]$ docker exec -ti pingbot /bin/bash
root@16f678ae9741:/usr/src/app# cat main.py
from telegram import Bot
from pythonping import ping
import time
import yaml
from libs.host import address

def init():

    """
    Здесь парсим конфиг файл и подключаем бота, запоминаем
    интервал, userid и передаем список хостов функции set_hosts
    """

    global bot, userid, interval

    interval = 30

    with open('/usr/src/app/config.yaml') as f:
        try:
            docs = yaml.load_all(f, Loader=yaml.FullLoader)

            for doc in docs:
                for k, v in doc.items():
                    if k == "botkey":
                        bot = Bot(v)
                    elif k == "userid":
                        userid = v
                    elif k == "hosts":
                        set_hosts(v)
                    elif k == "interval":
                        interval = int(v)

        except yaml.YAMLError as exc:
            print(exc)

def set_hosts(hosts):

    """
    Здесь парсим список хостов и передаем их в массив
    """

    global hosts_list
    hosts_list = []

    for item in hosts:
        ac = item.split(":")
        hosts_list.append(address(ac[0], ac[1]))

def send_message(message):

    """
    Посылаем сообщение пользователю
    """

    bot.send_message(userid, message, parse_mode='HTML', disable_web_page_preview=True)

def ping_host(address):

    """
    Логика приложения. Если статус хоста изменился, посылается сообщение пользователю.
    """

    status = ping_url(address.address)
    
    if status != address.status:
        send_message(address.comment + ( " is unresolwed" if status is None else " is up" if status else " is down"))
        address.status = status

def ping_url(url):

    """
    Пинг хоста. Response list - это ответ библиотеки ping. По умолчанию она
    посылает четыре пакета. Если хотя бы один раз пинг успешен, хост активен
    """

    try:
        response_list = ping(url)
    except:
        return None

    return sum(1 for x in response_list if x.success) > 0

def main():

    """
    Бесконечный цикл, который пингует сервисы один за другим.
    """

    init()

    while True:

        for host in hosts_list:
            ping_host(host)

**Comment by stTheme** [comment]
I'll look into it, let you know tomorrow

**Comment by slytomcat** [comment]
Yes, it's my mistake - I didn't changed the docer-compose.yaml. It started all time old 1.0 version.

I forgot that docer-compose.yaml contain image version.

**Pull request closed without merging**
